# CREATE DUMMY

In [16]:
import pandas as pd
import numpy as np
import random

# Jumlah baris data dummy
n = 200  

# Set seed biar hasil reproducible
random.seed(42)
np.random.seed(42)

# Daftar kolom sesuai data asli
columns = [
    "Usia Kepala Rumah Tangga", "Pendidikan Terakhir", "Status Petani",
    "Jumlah Tanggungan Keluarga (termasuk Kepala Keluarga)",
    "Luas lahan yang dikelola", "Status Kepemilikan Lahan",
    "Komoditas Utama yang ditanam", "Pola Tanam", "Sistem Irigasi",
    "Frekuensi Panen per Tahun", "Produksi Rata - Rata per Panen (Kwintal/Ha)",
    "Harga Jual Rata-Rata Hasil Panen Utama (Rp/kg)",
    "Pernah Gagal Panen dalam 5 Tahun Terakhir?",
    "Pengeluaran Rata-Rata Benih per Tahun (Rp)",
    "Pengeluaran Rata-Rata Pupuk per Tahun (Rp)",
    "Pengeluaran Rata-Rata Biaya Perawatan per Tahun (Rp)", "Stok Pupuk Saat Ini",
    "Menerima Subsidi Benih/Pupuk Pemerintah?",
    "Pernah Mengikuti Pelatihan dari Dinas/Kementerian?",
    "Sumber Utama Pangan Pokok", "Pernah Kehabisan Pangan Pokok dalam 3 Bulan Terakhir?",
    "Status Kemandirian Pangan Rumah Tangga", "Cadangan Pangan Keluarga dari Hasil Panen?",
    "Strategi Saat Kekurangan Pangan atau Gagal Panen",
    "Keikutsertaan dalam Koperasi atau Organisasi Tani",
    "Pernah Menerima Bantuan Pangan Pemerintah?", "Sumber Pinjaman Utama Saat Darurat",
    "Akses ke Informasi Pertanian (cuaca, harga, dll)",
    "Sumber Informasi Pertanian Utama", "Apakah mempunyai pekerjaan sampingan?",
    "Pernah Terdampak Kekeringan Ekstrem dalam 5 Tahun Terakhir?",
    "Kondisi Tanah Dominan (berdasarkan persepsi petani)", "Apakah pola tanam berubah akibat iklim?"
]

# Pilihan untuk kolom kategorikal
pendidikan = ["SD", "SMP", "SMA", "Diploma", "Sarjana"]
status_petani = ["Petani Pemilik", "Petani Penggarap", "Buruh Tani"]
status_lahan = ["Milik Sendiri", "Sewa", "Bagi Hasil"]
komoditas = ["Padi", "Jagung", "Kedelai", "Cabai", "Bawang"]
pola_tanam = ["Monokultur", "Tumpangsari", "Rotasi"]
irigasi = ["Irigasi Teknis", "Sumur", "Tadah Hujan"]
stok_pupuk = ["Ada", "Habis"]
ya_tidak = ["Ya", "Tidak"]
sumber_pangan = ["Panen Sendiri", "Beli Pasar", "Bantuan"]
strategi_kurang_pangan = ["Pinjam Uang", "Kurangi Konsumsi", "Jual Aset"]
koperasi = ["Ya", "Tidak"]
sumber_pinjam = ["Koperasi", "Bank", "Tetangga"]
akses_info = ["Mudah", "Sedang", "Sulit"]
sumber_info = ["Penyuluh", "Internet", "Tetangga"]
kondisi_tanah = ["Subur", "Sedang", "Kurang Subur"]

# Generate data dummy
data = []
for _ in range(n):
    usia = random.randint(25, 65)
    pend = random.choice(pendidikan)
    status = random.choice(status_petani)
    tanggungan = random.randint(2, 7)
    luas = round(random.uniform(0.1, 5.0), 2)
    kepemilikan = random.choice(status_lahan)
    kom = random.choice(komoditas)
    pola = random.choice(pola_tanam)
    irig = random.choice(irigasi)
    frek_panen = random.randint(1, 4)
    produksi = round(random.uniform(2.0, 8.0), 2)
    harga = random.randint(3000, 8000)
    gagal_panen = random.choice(ya_tidak)
    biaya_benih = random.randint(500000, 2000000)
    biaya_pupuk = random.randint(500000, 3000000)
    biaya_perawatan = random.randint(1000000, 5000000)
    stok = random.choice(stok_pupuk)
    subsidi = random.choice(ya_tidak)
    pelatihan = random.choice(ya_tidak)
    sumber_pokok = random.choice(sumber_pangan)
    kehabisan_pangan = random.choice(ya_tidak)
    kemandirian = random.choice(["Mandiri", "Rentan", "Tidak Mandiri"])
    cadangan = random.choice(ya_tidak)
    strategi = random.choice(strategi_kurang_pangan)
    koperasi_org = random.choice(koperasi)
    bantuan_pangan = random.choice(ya_tidak)
    pinjaman = random.choice(sumber_pinjam)
    akses = random.choice(akses_info)
    sumber_informasi = random.choice(sumber_info)
    pekerjaan_sampingan = random.choice(ya_tidak)
    kekeringan = random.choice(ya_tidak)
    tanah = random.choice(kondisi_tanah)
    perubahan_iklim = random.choice(ya_tidak)

    row = [usia, pend, status, tanggungan, luas, kepemilikan, kom, pola, irig,
           frek_panen, produksi, harga, gagal_panen, biaya_benih, biaya_pupuk,
           biaya_perawatan, stok, subsidi, pelatihan, sumber_pokok, kehabisan_pangan,
           kemandirian, cadangan, strategi, koperasi_org, bantuan_pangan,
           pinjaman, akses, sumber_informasi, pekerjaan_sampingan,
           kekeringan, tanah, perubahan_iklim]
    data.append(row)

# Buat DataFrame
df = pd.DataFrame(data, columns=columns)

# Save ke CSV
output_path = "dummy_ketahanan_pangan.csv"
df.to_csv(output_path, index=False, encoding='utf-8-sig')

print(f"✅ Data dummy berhasil dibuat dan disimpan sebagai: {output_path}")
df.head()

✅ Data dummy berhasil dibuat dan disimpan sebagai: dummy_ketahanan_pangan.csv

,Usia Kepala Rumah Tangga,Pendidikan Terakhir,Status Petani,Jumlah Tanggungan Keluarga (termasuk Kepala Keluarga),Luas lahan yang dikelola,Status Kepemilikan Lahan,Komoditas Utama yang ditanam,Pola Tanam,Sistem Irigasi,Frekuensi Panen per Tahun,...,Strategi Saat Kekurangan Pangan atau Gagal Panen,Keikutsertaan dalam Koperasi atau Organisasi Tani,Pernah Menerima Bantuan Pangan Pemerintah?,Sumber Pinjaman Utama Saat Darurat,"Akses ke Informasi Pertanian (cuaca, harga, dll)",Sumber Informasi Pertanian Utama,Apakah mempunyai pekerjaan sampingan?,Pernah Terdampak Kekeringan Ekstrem dalam 5 Tahun Terakhir?,Kondisi Tanah Dominan (berdasarkan persepsi petani),Apakah pola tanam berubah akibat iklim?
0,65,SD,Petani Pemilik,7,1.45,Milik Sendiri,Jagung,Rotasi,Irigasi Teknis,1,...,Pinjam Uang,Ya,Tidak,Bank,Sedang,Penyuluh,Ya,Tidak,Subur,Ya
1,49,SD,Petani Penggarap,4,3.06,Milik Sendiri,Cabai,Rotasi,Irigasi Teknis,4,...,Kurangi Konsumsi,Tidak,Tidak,Tetangga,Sedang,Penyuluh,Tidak,Tidak,Subur,Tidak
2,29,Sarjana,Buruh Tani,3,2.72,Milik Sendiri,Jagung,Tumpangsari,Sumur,3,...,Pinjam Uang,Tidak,Ya,Tetangga,Sedang,Internet,Tidak,Ya,Sedang,Ya
3,40,Sarjana,Buruh Tani,4,3.76,Sewa,Bawang,Tumpangsari,Sumur,2,...,Kurangi Konsumsi,Tidak,Tidak,Tetangga,Sedang,Tetangga,Ya,Ya,Kurang Subur,Tidak
4,46,SD,Petani Penggarap,5,0.87,Milik Sendiri,Kedelai,Rotasi,Irigasi Teknis,1,...,Kurangi Konsumsi,Ya,Ya,Koperasi,Sulit,Penyuluh,Ya,Tidak,Subur,Ya

# HASIL CREATE DUMMY (200)

In [17]:
import pandas as pd
from tabulate import tabulate
df = pd.read_csv("D:/Semester 7 (EVAL PA)/Try Code/dummy_ketahanan_pangan.csv")
df

,Usia Kepala Rumah Tangga,Pendidikan Terakhir,Status Petani,Jumlah Tanggungan Keluarga (termasuk Kepala Keluarga),Luas lahan yang dikelola,Status Kepemilikan Lahan,Komoditas Utama yang ditanam,Pola Tanam,Sistem Irigasi,Frekuensi Panen per Tahun,...,Strategi Saat Kekurangan Pangan atau Gagal Panen,Keikutsertaan dalam Koperasi atau Organisasi Tani,Pernah Menerima Bantuan Pangan Pemerintah?,Sumber Pinjaman Utama Saat Darurat,"Akses ke Informasi Pertanian (cuaca, harga, dll)",Sumber Informasi Pertanian Utama,Apakah mempunyai pekerjaan sampingan?,Pernah Terdampak Kekeringan Ekstrem dalam 5 Tahun Terakhir?,Kondisi Tanah Dominan (berdasarkan persepsi petani),Apakah pola tanam berubah akibat iklim?
0,65,SD,Petani Pemilik,7,1.45,Milik Sendiri,Jagung,Rotasi,Irigasi Teknis,1,...,Pinjam Uang,Ya,Tidak,Bank,Sedang,Penyuluh,Ya,Tidak,Subur,Ya
1,49,SD,Petani Penggarap,4,3.06,Milik Sendiri,Cabai,Rotasi,Irigasi Teknis,4,...,Kurangi Konsumsi,Tidak,Tidak,Tetangga,Sedang,Penyuluh,Tidak,Tidak,Subur,Tidak
2,29,Sarjana,Buruh Tani,3,2.72,Milik Sendiri,Jagung,Tumpangsari,Sumur,3,...,Pinjam Uang,Tidak,Ya,Tetangga,Sedang,Internet,Tidak,Ya,Sedang,Ya
3,40,Sarjana,Buruh Tani,4,3.76,Sewa,Bawang,Tumpangsari,Sumur,2,...,Kurangi Konsumsi,Tidak,Tidak,Tetangga,Sedang,Tetangga,Ya,Ya,Kurang Subur,Tidak
4,46,SD,Petani Penggarap,5,0.87,Milik Sendiri,Kedelai,Rotasi,Irigasi Teknis,1,...,Kurangi Konsumsi,Ya,Ya,Koperasi,Sulit,Penyuluh,Ya,Tidak,Subur,Ya
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,48,SD,Buruh Tani,5,4.81,Milik Sendiri,Jagung,Rotasi,Tadah Hujan,3,...,Jual Aset,Tidak,Tidak,Bank,Sedang,Internet,Tidak,Ya,Subur,Tidak
196,61,SMA,Petani Pemilik,7,2.42,Milik Sendiri,Bawang,Monokultur,Tadah Hujan,3,...,Pinjam Uang,Ya,Ya,Tetangga,Sulit,Penyuluh,Tidak,Tidak,Subur,Tidak
197,40,Diploma,Petani Pemilik,6,4.32,Sewa,Padi,Monokultur,Tadah Hujan,2,...,Pinjam Uang,Tidak,Tidak,Bank,Sedang,Internet,Ya,Tidak,Kurang Subur,Tidak
198,55,SMA,Petani Pemilik,6,4.36,Milik Sendiri,Kedelai,Tumpangsari,Sumur,3,...,Jual Aset,Tidak,Tidak,Tetangga,Sulit,Penyuluh,Ya,Tidak,Kurang Subur,Ya
199,45,Sarjana,Petani Pemilik,7,0.14,Milik Sendiri,Padi,Tumpangsari,Irigasi Teknis,1,...,Jual Aset,Ya,Ya,Tetangga,Mudah,Internet,Ya,Ya,Kurang Subur,Ya